### ISSUE TITLE
Lists dont show up

### ISSUE THREAD

**Issue by FlashlightET** [forkphorus/forkphorus.github.io#2]
Lists dont show up
![image](https://user-images.githubusercontent.com/29938499/59350716-cc56fe80-8cea-11e9-8829-f4192ace0e1f.png)

----
Project URL: (no url)
Project ID: local sb2
https://beefchips.github.io/beefchips/#.sb2
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

**Comment by GarboMuffin** [comment]
beefchips is an outdated and unmaintained version of forkphorus that just set the FPS to 120. It is no longer needed because forkphorus lets you set the framerate through its settings menu. Try to reproduce it in the latest version of forkphorus: [forkphorus.github.io](forkphorus.github.io)
