### ISSUE TITLE
The operator.sb3 always failed when I test it

### ISSUE THREAD

**Issue by scratchusernamemrtbts** [forkphorus/forkphorus.github.io#3]
It always said that operator.sb3 failed I’m not sure if it’s the tester bug or it always failed like that

**Comment by GarboMuffin** [comment]
this isn't the place to report bugs (go here: https://github.com/forkphorus/forkphorus/issues) but that should be fixed now

**Comment by scratchusernamemrtbts** [comment]
Ok, thanks
